[package]
name = "cpp2rust-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
cpp2rust = { path = "../cpp2rust" }
log = "0.4"
anyhow = "1.0"
clap = { version = "4.4", features = ["derive", "env"] }
env_logger = "0.11"
chrono = "0.4"
tokio = { version = "1", features = ["full"] }
